### ISSUE TITLE
Como arrendatario puedo iniciar sesión para utilizar todas las funciionalidades de la página. 

### ISSUE THREAD

**Issue by capcaz99** [ADSI-ITAM-2017/ataraxia#11]
CA:
-Botón para iniciar sesión en todas las páginas en la esquina superior derecha. 
-que al dar clic en el botón aparezca una ventana en donde pueda introducir mi nombre de usuario, contraseña y después dar click en un botón para iniciar sesión.

**Comment by jpfernandez11** [comment]
Estamos cerrando por estar duplicado
